# Maps conference shorthand to full name
conference_name = {
    "ACC": "Atlantic Coast Conference",
    "American": "American Athletic Conference",
    "Big 12": "Big 12 Conference",
    "Big Ten": "Big Ten Conference",
    "CUSA": "Conference USA",
    "Ind": "Independent",
    "MAC": "Mid-American Conference",
    "MWC": "Mountain West Conference",
    "Pac-12": "Pacific-12 Conference",
    "SEC": "Southeastern Conference",
    "Sun Belt": "Sun Belt Conference"
}

# Maps college name to mascot
college_mascot = {
    "Air Force": "Falcons",
    "Akron": "Zips",
    "Alabama": "Crimson Tide",
    "Appalachian State": "Mountaineers",
    "Arizona": "Wildcats",
    "Arizona State": "Sun Devils",
    "Arkansas": "Razorbacks",
    "Arkansas State": "Red Wolves",
    "Army": "Black Knights",
    "Auburn": "Tigers",
    "BYU": "Cougars",
    "Ball State": "Cardinals",
    "Baylor": "Bears",
    "Boise State": "Broncos",
    "Boston College": "Eagles",
    "Bowling Green": "Falcons",
    "Buffalo": "Bulls",
    "California": "Golden Bears",
    "Central Michigan": "Chippewas",
    "Charlotte": "49ers",
    "Cincinnati": "Bearcats",
    "Clemson": "Tigers",
    "Coastal Carolina": "Chanticleers",
    "Colorado": "Buffaloes",
    "Colorado State": "Rams",
    "Connecticut": "Huskies",
    "Duke": "Blue Devils",
    "East Carolina": "Pirates",
    "Eastern Michigan": "Eagles",
    "Florida": "Gators",
    "Florida Atlantic": "Owls",
    "Florida International": "Panthers",
    "Florida State": "Seminoles",
    "Fresno State": "Bulldogs",
    "Georgia": "Bulldogs",
    "Georgia Southern": "Eagles",
    "Georgia State": "Panthers",
    "Georgia Tech": "Yellow Jackets",
    "Hawaii": "Rainbow Warriors",
    "Houston": "Cougars",
    "Illinois": "Fighting Illini",
    "Indiana": "Hoosiers",
    "Iowa": "Hawkeyes",
    "Iowa State": "Cyclones",
    "Jacksonville State": "Gamecocks",
    "James Madison": "Dukes",
    "Kansas": "Jayhawks",
    "Kansas State": "Wildcats",
    "Kennesaw State": "Owls",
    "Kent State": "Golden Flashes",
    "Kentucky": "Wildcats",
    "LSU": "Tigers",
    "Liberty": "Flames",
    "Louisiana": "Ragin' Cajuns",
    "Louisiana Tech": "Bulldogs",
    "Louisiana-Monroe": "Warhawks",
    "Louisville": "Cardinals",
    "Marshall": "Thundering Herd",
    "Maryland": "Terrapins",
    "Massachusetts": "Minutemen",
    "Memphis": "Tigers",
    "Miami (FL)": "Hurricanes",
    "Miami (OH)": "RedHawks",
    "Michigan": "Wolverines",
    "Michigan State": "Spartans",
    "Middle Tennessee State": "Blue Raiders",
    "Minnesota": "Golden Gophers",
    "Mississippi State": "Bulldogs",
    "Missouri": "Tigers",
    "Navy": "Midshipmen",
    "Nebraska": "Cornhuskers",
    "Nevada": "Wolf Pack",
    "Nevada-Las Vegas": "Rebels",
    "New Mexico": "Lobos",
    "New Mexico State": "Aggies",
    "North Carolina": "Tar Heels",
    "North Carolina State": "Wolfpack",
    "North Texas": "Mean Green",
    "Northern Illinois": "Huskies",
    "Northwestern": "Wildcats",
    "Notre Dame": "Fighting Irish",
    "Ohio": "Bobcats",
    "Ohio State": "Buckeyes",
    "Oklahoma": "Sooners",
    "Oklahoma State": "Cowboys",
    "Old Dominion": "Monarchs",
    "Ole Miss": "Rebels",
    "Oregon": "Ducks",
    "Oregon State": "Beavers",
    "Penn State": "Nittany Lions",
    "Pitt": "Panthers",
    "Purdue": "Boilermakers",
    "Rice": "Owls",
    "Rutgers": "Scarlet Knights",
    "SMU": "Mustangs",
    "Sam Houston": "Bearkats",
    "San Diego State": "Aztecs",
    "San Jose State": "Spartans",
    "South Alabama": "Jaguars",
    "South Carolina": "Gamecocks",
    "South Florida": "Bulls",
    "Southern Mississippi": "Golden Eagles",
    "Stanford": "Cardinal",
    "Syracuse": "Orange",
    "Temple": "Owls",
    "Tennessee": "Volunteers",
    "Texas": "Longhorns",
    "Texas A&M": "Aggies",
    "Texas Christian": "Horned Frogs",
    "Texas State": "Bobcats",
    "Texas Tech": "Red Raiders",
    "Toledo": "Rockets",
    "Troy": "Trojans",
    "Tulane": "Green Wave",
    "Tulsa": "Golden Hurricane",
    "UAB": "Blazers",
    "UCF": "Knights",
    "UCLA": "Bruins",
    "USC": "Trojans",
    "UTEP": "Miners",
    "UTSA": "Roadrunners",
    "Utah": "Utes",
    "Utah State": "Aggies",
    "Vanderbilt": "Commodores",
    "Virginia": "Cavaliers",
    "Virginia Tech": "Hokies",
    "Wake Forest": "Demon Deacons",
    "Washington": "Huskies",
    "Washington State": "Cougars",
    "West Virginia": "Mountaineers",
    "Western Kentucky": "Hilltoppers",
    "Western Michigan": "Broncos",
    "Wisconsin": "Badgers",
    "Wyoming": "Cowboys",
}

# Maps file extension of roster to college name
file_extension_to_college = {
    "air_force": "Air Force",
    "akron": "Akron",
    "alabama": "Alabama",
    "appalachian_state":"Appalachian State",
    "arizona":"Arizona",
    "arizona_state":"Arizona State",
    "arkansas":"Arkansas",
    "arkansas_state":"Arkansas State",
    "army":"Army",
    "auburn":"Auburn",
    "byu":"BYU",
    "ball_state":"Ball State",
    "baylor":"Baylor",
    "boise_state":"Boise State",
    "boston_college":"Boston College",
    "bowling_green":"Bowling Green",
    "buffalo":"Buffalo",
    "california":"California",
    "central_michigan":"Central Michigan",
    "charlotte":"Charlotte",
    "cincinnati":"Cincinnati",
    "clemson":"Clemson",
    "coastal_carolina":"Coastal Carolina",
    "colorado":"Colorado",
    "colorado_state":"Colorado State",
    "connecticut":"Connecticut",
    "duke":"Duke",
    "east_carolina":"East Carolina",
    "eastern_michigan":"Eastern Michigan",
    "florida":"Florida",
    "florida_atlantic":"Florida Atlantic",
    "florida_international":"Florida International",
    "florida_state":"Florida State",
    "fresno_state":"Fresno State",
    "georgia":"Georgia",
    "georgia_southern":"Georgia Southern",
    "georgia_state":"Georgia State",
    "georgia_tech":"Georgia Tech",
    "hawaii":"Hawaii",
    "houston":"Houston",
    "illinois":"Illinois",
    "indiana":"Indiana",
    "iowa":"Iowa",
    "iowa_state":"Iowa State",
    "jacksonville_state":"Jacksonville State",
    "james_madison":"James Madison",
    "kansas":"Kansas",
    "kansas_state":"Kansas State",
    "kennesaw_state":"Kennesaw State",
    "kent_state":"Kent State",
    "kentucky":"Kentucky",
    "lsu":"LSU",
    "liberty":"Liberty",
    "louisiana":"Louisiana",
    "louisiana_tech":"Louisiana Tech",
    "louisiana_monroe":"Louisiana-Monroe",
    "louisville":"Louisville",
    "marshall":"Marshall",
    "maryland":"Maryland",
    "massachusetts":"Massachusetts",
    "memphis":"Memphis",
    "miami_fl":"Miami (FL)",
    "miami_oh":"Miami (OH)",
    "michigan":"Michigan",
    "michigan_state":"Michigan State",
    "middle_tennessee_state":"Middle Tennessee State",
    "minnesota":"Minnesota",
    "mississippi_state":"Mississippi State",
    "missouri":"Missouri",
    "navy":"Navy",
    "nebraska":"Nebraska",
    "nevada":"Nevada",
    "nevada_las_vegas":"Nevada-Las Vegas",
    "new_mexico":"New Mexico",
    "new_mexico_state":"New Mexico State",
    "north_carolina":"North Carolina",
    "north_carolina_state":"North Carolina State",
    "north_texas":"North Texas",
    "northern_illinois":"Northern Illinois",
    "northwestern":"Northwestern",
    "notre_dame":"Notre Dame",
    "ohio":"Ohio",
    "ohio_state":"Ohio State",
    "oklahoma":"Oklahoma",
    "oklahoma_state":"Oklahoma State",
    "old_dominion":"Old Dominion",
    "ole_miss":"Ole Miss",
    "oregon":"Oregon",
    "oregon_state":"Oregon State",
    "penn_state":"Penn State",
    "pitt":"Pitt",
    "purdue":"Purdue",
    "rice":"Rice",
    "rutgers":"Rutgers",
    "smu":"SMU",
    "sam_houston":"Sam Houston",
    "san_diego_state":"San Diego State",
    "san_jose_state":"San Jose State",
    "south_alabama":"South Alabama",
    "south_carolina":"South Carolina",
    "south_florida":"South Florida",
    "southern_mississippi":"Southern Mississippi",
    "stanford":"Stanford",
    "syracuse":"Syracuse",
    "temple":"Temple",
    "tennessee":"Tennessee",
    "texas":"Texas",
    "texas_am":"Texas A&M",
    "texas_christian":"Texas Christian",
    "texas_state":"Texas State",
    "texas_tech":"Texas Tech",
    "toledo":"Toledo",
    "troy":"Troy",
    "tulane":"Tulane",
    "tulsa":"Tulsa",
    "uab":"UAB",
    "ucf":"UCF",
    "ucla":"UCLA",
    "usc":"USC",
    "utep":"UTEP",
    "utsa":"UTSA",
    "utah":"Utah",
    "utah_state":"Utah State",
    "vanderbilt":"Vanderbilt",
    "virginia":"Virginia",
    "virginia_tech":"Virginia Tech",
    "wake_forest":"Wake Forest",
    "washington":"Washington",
    "washington_state":"Washington State",
    "west_virginia":"West Virginia",
    "western_kentucky":"Western Kentucky",
    "western_michigan":"Western Michigan",
    "wisconsin":"Wisconsin",
    "wyoming":"Wyoming", 
}

# Maps college shorthand to standard name
college_shorthand_to_name = {
  "Brigham Young": "BYU",
  "Bowling Green State": "Bowling Green",
  "TCU": "Texas Christian",
  "UNLV": "Nevada-Las Vegas"
}

# Maps position abbreviation to full name
position_name = {
    "CB": "Cornerback",
    "DB": "Defensive Back",
    "DE": "Defensive End",
    "DL": "Defensive Line",
    "DT": "Defensive Tackle",
    "FB": "Fullback",
    "K": "Kicker",
    "LB": "Linebacker",
    "LS": "Long Snapper",
    "N/A": "Not Provided",
    "OC": "Offensive Center",
    "OG": "Offensive Guard",
    "OL": "Offensive Line",
    "OT": "Offensive Tackle",
    "P": "Punter",
    "QB": "Quarterback",
    "RB": "Running Back",
    "S": "Safety",
    "TE": "Tight End",
    "WR": "Wide Receiver",
}

# Maps class abbreviation to full name
class_name = {
    "FR": "Freshman",
    "JR": "Junior",
    "N/A": "Not Provided",
    "SO": "Sophomore",
    "SR": "Senior",
}