college_to_extension = {
    "Air Force": "air_force",
    "Akron": "akron",
    "Alabama": "alabama",
    "Appalachian State": "appalachian_state",
    "Arizona State": "arizona_state",
    "Arizona": "arizona",
    "Arkansas State": "arkansas_state",
    "Arkansas": "arkansas",
    "Army": "army",
    "Auburn": "auburn",
    "Ball State": "ball_state",
    "Baylor": "baylor",
    "Boise State": "boise_state",
    "Boston College": "boston_college",
    "Bowling Green": "bowling_green",
    "Buffalo": "buffalo",
    "BYU": "byu",
    "California": "california",
    "Central Michigan": "central_michigan",
    "Charlotte": "charlotte",
    "Cincinnati": "cincinnati",
    "Clemson": "clemson",
    "Coastal Carolina": "coastal_carolina",
    "Colorado State": "colorado_state",
    "Colorado": "colorado",
    "Connecticut": "connecticut",
    "Duke": "duke",
    "East Carolina": "east_carolina",
    "Eastern Michigan": "eastern_michigan",
    "Florida Atlantic": "florida_atlantic",
    "Florida International": "florida_international",
    "Florida State": "florida_state",
    "Florida": "florida",
    "Fresno State": "fresno_state",
    "Georgia Southern": "georgia_southern",
    "Georgia State": "georgia_state",
    "Georgia Tech": "georgia_tech",
    "Georgia": "georgia",
    "Hawaii": "hawaii",
    "Houston": "houston",
    "Illinois": "illinois",
    "Indiana": "indiana",
    "Iowa State": "iowa_state",
    "Iowa": "iowa",
    "Jacksonville State": "jacksonville_state",
    "James Madison": "james_madison",
    "Kansas State": "kansas_state",
    "Kansas": "kansas",
    "Kennesaw State": "kennesaw_state",
    "Kent State": "kent_state",
    "Kentucky": "kentucky",
    "Liberty": "liberty",
    "Louisiana-Monroe": "louisiana_monroe",
    "Louisiana Tech": "louisiana_tech",
    "Louisiana": "louisiana",
    "LSU": "lsu",
    "Louisville": "louisville",
    "Marshall": "marshall",
    "Maryland": "maryland",
    "Massachusetts": "massachusetts",
    "Memphis": "memphis",
    "Miami (FL)": "miami_fl",
    "Miami (OH)": "miami_oh",
    "Michigan State": "michigan_state",
    "Michigan": "michigan",
    "Middle Tennessee State": "middle_tennessee_state",
    "Minnesota": "minnesota",
    "Mississippi State": "mississippi_state",
    "Missouri": "missouri",
    "Navy": "navy",
    "Nebraska": "nebraska",
    "Nevada-Las Vegas": "nevada_las_vegas",
    "Nevada": "nevada",
    "New Mexico State": "new_mexico_state",
    "New Mexico": "new_mexico",
    "North Carolina State": "north_carolina_state",
    "North Carolina": "north_carolina",
    "North Texas": "north_texas",
    "Northern Illinois": "northern_illinois",
    "Northwestern": "northwestern",
    "Notre Dame": "notre_dame",
    "Ohio State": "ohio_state",
    "Ohio": "ohio",
    "Oklahoma State": "oklahoma_state",
    "Oklahoma": "oklahoma",
    "Old Dominion": "old_dominion",
    "Ole Miss": "ole_miss",
    "Oregon State": "oregon_state",
    "Oregon": "oregon",
    "Penn State": "penn_state",
    "Pitt": "pitt",
    "Purdue": "purdue",
    "Rice": "rice",
    "Rutgers": "rutgers",
    "Sam Houston": "sam_houston",
    "San Diego State": "san_diego_state",
    "San Jose State": "san_jose_state",
    "SMU": "smu",
    "South Alabama": "south_alabama",
    "South Carolina": "south_carolina",
    "South Florida": "south_florida",
    "Southern Mississippi": "southern_mississippi",
    "Stanford": "stanford",
    "Syracuse": "syracuse",
    "Temple": "temple",
    "Tennessee": "tennessee",
    "Texas Christian": "texas_christian",
    "Texas A&M": "texas_am",
    "Texas State": "texas_state",
    "Texas Tech": "texas_tech",
    "Texas": "texas",
    "Toledo": "toledo",
    "Troy": "troy",
    "Tulane": "tulane",
    "Tulsa": "tulsa",
    "UAB": "uab",
    "UCF": "ucf",
    "UCLA": "ucla",
    "USC": "usc",
    "Utah State": "utah_state",
    "Utah": "utah",
    "UTEP": "utep",
    "UTSA": "utsa",
    "Vanderbilt": "vanderbilt",
    "Virginia": "virginia",
    "Virginia Tech": "virginia_tech",
    "Wake Forest": "wake_forest",
    "Washington State": "washington_state",
    "Washington": "washington",
    "West Virginia": "west_virginia",
    "Western Kentucky": "western_kentucky",
    "Western Michigan": "western_michigan",
    "Wisconsin": "wisconsin",
    "Wyoming": "wyoming",
}

conference_to_extension = {
    "ACC": "acc",
    "American": "american",
    "Big 12": "big_12",
    "Big Ten": "big_ten",
    "CUSA": "cusa",
    "Ind": "independents",
    "MAC": "mac",
    "MWC": "mwc",
    "Pac-12": "pac_12",
    "SEC": "sec",
    "Sun Belt": "sun_belt",
}